project:
  type: website
  output-dir: docs

website:
  title: "Learning - Security"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: initiative.qmd
        text: Initiative
      - href: act-ii.qmd
        text: Act II
      - href: act-iii.qmd
        text: Act III

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
